# -*- coding: utf-8 -*-
"""Elevate_Lab_Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbHw_CKeAkhfAQcN1oNEVSSQZK2jDuAZ

# **📌 Task 1: Data Cleaning and Preprocessing**


---



### **📝 Introduction**

The objective of this task is to clean and prepare a raw dataset by identifying and resolving common data quality issues such as missing values, duplicates, inconsistent text formats, and incorrect data types. Clean data is essential for accurate and meaningful analysis.

For this task, we used the **Customer Personality Analysis** dataset from Kaggle, which contains detailed customer demographic and behavioral information. Using Python and the Pandas library, the dataset was processed to:

- Identify and handle missing values
- Remove duplicate entries
- Standardize text data (e.g., education levels, marital status)
- Convert date fields to a consistent format (`dd-mm-yyyy`)
- Rename columns for consistency and ease of use
- Validate and correct data types (e.g., numerical values as `int`, dates as `datetime`)

This preprocessing ensures that the dataset is structured, reliable, and ready for further analysis or model building.
"""

import pandas as pd

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/marketing_campaign.csv", sep='\t')

print(df.shape)
print(df.columns)
print(df.head())

# Missing Values
print(df.isnull().sum())

#Duplicate Values
print(df.duplicated().sum())

#Column Formatting
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns)

#Converting the daet in Standard Format
df['dt_customer'] = pd.to_datetime(df['dt_customer'], format='%d-%m-%Y')

print(df['education'].value_counts())
print(df['marital_status'].value_counts())

print(df['year_birth'].describe())
print(df['income'].describe())

print(df['income'].isnull().sum())

# Missing Values (fillna)
df['income'] = df['income'].fillna(df['income'].median())

# Categorical Standardization
df['education'] = df['education'].replace({'2n Cycle': 'Master'})

# Categorical Standardization
df['marital_status'] = df['marital_status'].replace({
    'Alone': 'Other',
    'Absurd': 'Other',
    'YOLO': 'Other'
})

# Data Type Validation
print(df.dtypes)

df.head()

"""## **Data Cleaning Summary – Customer Personality Analysis**

This section outlines the key data cleaning steps performed on the dataset:

### ✅ Missing Values
- Found 24 missing values in the `Income` column.
- Filled them using the **median income** to preserve rows.

### ✅ Duplicates
- Checked for duplicates using `.duplicated()`.
- Result: **No duplicate rows** found.

### ✅ Column Formatting
- Renamed all columns to **lowercase** with **underscores** for consistency.

### ✅ Date Conversion
- Converted `dt_customer` from string to proper **datetime format** (`datetime64[ns]`).

### ✅ Categorical Standardization
- Merged `"2n Cycle"` into `"Master"` under the `education` column.
- Replaced invalid `marital_status` entries like `"YOLO"`, `"Absurd"`, and `"Alone"` with `"Other"`.

### ✅ Data Type Validation
- Ensured proper types:
  - `year_birth`, `kidhome`, `teenhome`, etc. → `int64`
  - `income` → `float64`
  - `dt_customer` → `datetime64[ns]`

> ✅ Final cleaned dataset shape: **(2216, 29)**

"""